name: Run Pytest on Push

on:
  push:
    branches:
      - main  # Cambia "main" si tu rama principal tiene otro nombre

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0'  # Cambia según la versión que uses

      # Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Asegúrate de tener este archivo con tus dependencias

      # Ejecutar Pytest
      - name: Run tests
        run: pytest -s automation/tests/test_profile.py

      # Guardar reportes como artifacts
      - name: Upload test reports
        if: always()  # Asegúrate de guardar los reportes incluso si las pruebas fallan
        uses: actions/upload-artifact@v3
        with:
          name: test-reports  # Nombre que aparecerá en los artifacts
          path: report        # Ruta de la carpeta que contiene los reportes
